apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ethdns-xyz
spec:
  secretName: ethdns-xyz-cert
  commonName: 'ethdns.xyz'
  dnsNames:
  - ethdns.xyz
  issuerRef:
    name: letsencrypt-prod
