apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ethlab-xyz
spec:
  secretName: ethlab-xyz-cert
  commonName: 'ethlab.xyz'
  dnsNames:
  - ethlab.xyz
  issuerRef:
    name: letsencrypt-prod
