apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: eth-domains
spec:
  secretName: eth-domains-cert
  commonName: '*.eth.domains'
  dnsNames:
  - eth.domains
  issuerRef:
    name: letsencrypt-prod
