apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: eth-link
spec:
  secretName: eth-link-cert
  commonName: '*.eth.link'
  dnsNames:
  - eth.link
  issuerRef:
    name: letsencrypt-prod
