apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
data:
  Corefile: |
    (ens) {
      log
      reload
      doh {
        upstream https://eth.resolver.cloudflare-eth.com/dns-query
      }
      file /etc/coredns/eth.zone eth.
      errors
    }
    eth.link. {
      rewrite stop name exact _cf-custom-hostname.eth.link _cf-custom-hostname.eth.link
      rewrite stop {
        name regex (.*\.|)eth\.link {1}eth
        answer name (.*\.|)eth {1}eth.link
      }
      import ens
      health
    }
    https://. {
      tls /etc/ssl/ethdns.xyz/tls.crt /etc/ssl/ethdns.xyz/tls.key
      import ens
      forward . 8.8.8.8
    }
  eth.zone: |
    $ORIGIN eth.
    @ 3600 IN SOA ns1.ethdns.xyz. hostmaster.eth. (
        2021011903 ; serial
        7200       ; refresh (2 hours)
        3600       ; retry (1 hour)
        1209600    ; expire (2 weeks)
        3600       ; minimum (1 hour)
      )
    @ IN NS ns1.ethdns.xyz.
    @ IN NS ns2.ethdns.xyz.
    @ IN NS ns3.ethdns.xyz.
    @ IN TXT ca3-ec826a62472740a482dfccb326cd44fb
    _cf-custom-hostname TXT d18810a4-0d66-4939-8c28-e59337be845d
    @ IN A 104.18.166.219
    @ IN A 104.18.165.219
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coredns
  labels:
    app: coredns
spec:
  replicas: %(coredns_replicas)d
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
        - name: coredns
          image: arachnid/coredns:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 53
            - containerPort: 8080
            - containerPort: 443
          args:
            - "-conf=/etc/coredns/Corefile"
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
            - name: ethdns-xyz-cert
              mountPath: /etc/ssl/ethdns.xyz
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#            initialDelaySeconds: 6
#            periodSeconds: 6
      volumes:
        - name: config-volume
          configMap:
            name: coredns-config
        - name: ethdns-xyz-cert
          secret:
            secretName: ethdns-xyz-cert
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-tcp
  labels:
    app: coredns
spec:
  ports:
  - port: 53
    protocol: TCP
    name: dns-tcp
  selector:
    app: coredns
  type: LoadBalancer
  loadBalancerIP: %(cluster_ip)s
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-doh
  labels:
    app: coredns
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: coredns
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-udp
  labels:
    app: coredns
spec:
  ports:
  - port: 53
    protocol: UDP
    name: dns-udp
  selector:
    app: coredns
  type: LoadBalancer
  loadBalancerIP: %(cluster_ip)s
