apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {

    }

    http {
      upstream default {
        server ipfs:8080;
      }

      server {
        listen *:80;
        listen *:443 ssl;
        server_name *.eth.domains;
        ssl_certificate /etc/ssl/eth.domains/tls.crt;
        ssl_certificate_key /etc/ssl/eth.domains/tls.key;

        location / {
          proxy_pass http://default;
          proxy_set_header Host $host;
        }
      }

      server {
        listen *:80;
        listen *:443 ssl;
        server_name ethlab.xyz;
        ssl_certificate /etc/ssl/ethlab.xyz/tls.crt;
        ssl_certificate_key /etc/ssl/ethlab.xyz/tls.key;

        location /dns-query {
          proxy_pass https://coredns-doh;
          proxy_set_header Host $host;
          proxy_ssl_session_reuse on;
        }
      }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.17.3
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
            - containerPort: 443
              hostPort: 443
              name: https
          securityContext:
            capabilities:
              add: ["NET_BIND_SERVICE"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx
            - name: eth-domains-cert
              mountPath: /etc/ssl/eth.domains
            - name: ethlab-xyz-cert
              mountPath: /etc/ssl/ethlab.xyz
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
        - name: eth-domains-cert
          secret:
            secretName: eth-domains-cert
        - name: ethlab-xyz-cert
          secret:
            secretName: ethlab-xyz-cert
