apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main
spec:
  tls:
  - secretName: eth-domains-cert
  rules:
  - http:
      paths:
      - backend:
          serviceName: ipfs
          servicePort: ipfs-gateway
